export const TURNON = 'turn_on';
export const TURNOFF = 'turn_off';
export const SYNCTRACK ='sync_track';
export const PAUSED = 'pause_on';
export const LOADING ='loading'
export const SYNCNEXTTRACKS = 'sync_next_tracks';
export const SYNCPOSITION = 'sync_current_position';
export const ADD_NEXTTRACK_LIST ='add_next_tracks';
export const APPEND_NEXTTRACK_LIST ='append_next_tracks';